title: DX推進室 デジタルツール利用ガイド
email: dx@scout.or.jp
description: >-
    デジタルツールを活用し、ボーイスカウト運動を継続するために使える各種ツールの使い方やガイドライン
集
baseurl: ""
url: ""
# twitter_username: jekyllrb
github_username:  Scout-Association-of-Japan

# Build settings
#theme: minima
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
