site_name: ボーイスカウト日本連盟 デジタルツール利用ガイド
copyright: Copyright &copy; 2020- Scout Association of Japan
theme:
  name: material
  language: ja
  logo: images/saj_logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
  custom_dir: 'theme_custom'
extra_css:
  - stylesheets/additional.css
repo_url: https://github.com/Scout-Association-of-Japan/DX-promotion-guidelines
repo_name: Fork me on GitHub
extra:
  analytics:
    provider: google
    property: G-D2E61LC0JY
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ScoutingJapan
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/ScoutingJapan
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/scout.or.jp
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/scout_association_of_japan/
plugins:
  - search:
      lang: ja
  - git-revision-date
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - footnotes
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - ホーム:
    - ボーイスカウト日本連盟デジタルツール利用ガイド: index.md
  - Web会議ツール:
    - どの会議ツールを選んだらいいの?: web-meeting-guide/WhatShouldIChoose.md
  - ファイル共有:
    - Googleドライブでファイル共有をしてみよう: file-share/HowToUseGDrive.md
  - リモートデスクトップ:
    - リモートデスクトップを使ってみよう: remote-desktop/HowToUseChromeRD.md
  - よくある質問:
    - よくある質問集(FAQ): faq/index.md
  - フォーラム:
    - デジタルツール提供プログラム利用グループ: group/HowtoUseUserForum.md
